apiVersion: v1
kind: Namespace
metadata:
  name: services-observability
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
    istio.io/dataplane-mode: ambient
    openaether.io/managed: "true"
    openaether.io/sprint: "0.5.0-sprintC"
    openaether.io/component: "observability"
