apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: openaether-gateway
  namespace: services-gateway
  labels:
    openaether.io/managed: "true"
    openaether.io/sprint: "0.5.0-sprintB"
    openaether.io/component: "gateway"
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: openaether-tls
            namespace: services-gateway
      allowedRoutes:
        namespaces:
          from: All
