apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    # baseline: Kyverno background-controller utilise hostPID pour certaines ops.
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
    openaether.io/managed: "true"
    openaether.io/sprint: "0.5.0-sprint0"
    openaether.io/component: "kyverno"
