# Groupe 01 — Platform (priority classes + network policies de base)
---
# local-path-provisioner: installé par OpenTofu à l'init cluster, géré ici par Flux
# pour assurer la cohérence des StorageClasses (local-path + local-path-retain).
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-local-path-provisioner
  namespace: flux-system
spec:
  interval: 2m
  retryInterval: 30s
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: openaether
  path: ./apps/base/platform/local-path-provisioner
  prune: true
  wait: true
  dependsOn:
    - name: namespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-gateway-api
  namespace: flux-system
spec:
  interval: 2m
  retryInterval: 30s
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: openaether
  path: ./apps/base/platform/gateway-api
  prune: true
  wait: true
  dependsOn:
    - name: namespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-priority-classes
  namespace: flux-system
spec:
  interval: 2m
  retryInterval: 30s
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: openaether
  path: ./apps/base/platform/priority-classes
  prune: true
  wait: true
  dependsOn:
    - name: namespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-cilium-lb-ipam
  namespace: flux-system
spec:
  interval: 2m
  retryInterval: 30s
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: openaether
  path: ./apps/base/platform/cilium-lb-ipam
  prune: true
  wait: true
  dependsOn:
    - name: namespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-network-policies
  namespace: flux-system
spec:
  interval: 2m
  retryInterval: 30s
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: openaether
  path: ./apps/base/platform/network-policies
  prune: true
  wait: true
  dependsOn:
    - name: namespaces
