# NetworkPolicies (explicit allow-lists).
# NB: Cilium ignores native k8s NetworkPolicies — we use ONLY
# CiliumNetworkPolicy (L3/L4/L7 through cilium-envoy).
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - allow-dns.yaml
  - allow-kube-api.yaml
  - allow-cilium-health.yaml
  - allow-infra-egress-restricted.yaml
  - coredns-ingress-restricted.yaml
  - coredns-egress-hostdns.yaml
  - default-deny-all.yaml
