---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-operator-system
