apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - block-default-ns.yaml
  - require-security-context.yaml
  - restrict-privileged.yaml
  - restrict-image-registries.yaml
