apiVersion: v1
kind: Namespace
metadata:
  name: foundation-storage
  labels:
    pod-security.kubernetes.io/enforce: privileged
    istio.io/dataplane-mode: ambient
    openaether.io/managed: "true"
    openaether.io/sprint: "0.5.0-sprintC"
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
    openaether.io/managed: "true"
    openaether.io/sprint: "0.5.0-sprintC"
