apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    pod-security.kubernetes.io/enforce: privileged
    openaether.io/managed: "true"
    openaether.io/sprint: "0.5.0-sprintB"
    openaether.io/component: "cert-manager"
