apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Ressources Istio nécessitant les CRDs security.istio.io (installés par istio-base HelmRelease)
# Appliqués APRÈS que le Kustomization 'istio' soit Ready (wait: true)
resources:
  - peerauthentication-strict.yaml
  - authorizationpolicy-default-deny.yaml
  - authorizationpolicy-explicit-allows.yaml