apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# AuthorizationPolicies - appliqués APRÈS que les CRDs Istio soient installées
resources:
  - authorizationpolicy-default-deny.yaml
  - authorizationpolicy-explicit-allows.yaml